language: go
go:
  - 1.4
  - tip

before_script:
  - wget https://github.com/antirez/disque/archive/master.zip -O /tmp/disque.zip
  - cd /tmp && unzip disque.zip
  - cd /tmp/disque-master && make && make install
  - disque-server &
script:
  - go test -v
